# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

variables:
 - group: 'Test-Variables'

stages:
 - stage: Export
   displayName: 'Export'
   
   jobs:
     - job: Export
       displayName: 'Export Solution'
       pool:
        name: 'Azure Pipelines'
        vmImage: 'windows-latest'
       steps:
         - checkout: none
           displayName: 'Skip Source Checkout'

         - task: PowerShell@2
           displayName: 'Clone Source Control Repository To Workspace'
           inputs:
             targetType: 'inline'
             script: |
               write-host "$(Build.RequestedFor)"
               write-host "$(Build.RequestedForId)"
               write-host "$(Build.RequestedForEmail)"
               write-host "$(Build.Repository.Uri)"

               ${RepositoryAccessToken} = "$env:ADO_PAT_TOKEN"

               ${RepositoryURL} = “https://$(Build.RequestedForId):${RepositoryAccessToken}@$(hostname)/$(Build.Repository.Name)”
               ${ExitStatus} = git ls-remote --exit-code --heads ${RepositoryURL} $(Sales_Sol_Export_Branch_Name)
               if(${ExitStatus}.Length -gt 0)
               {
                 Write-host “Branch Exist”
                 }
           env:
             ADO_PAT_TOKEN: $(System.AccessToken)