# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

stages:
 - stage: Export
   displayName: 'Export'
   
   jobs:
     - job: Export
       displayName: 'Export Solution'
       pool:
        name: 'Azure Pipelines'
        vmImage: 'windows-latest'
       steps:
         - checkout: none
           displayName: 'Skip Source Checkout'

         - task: PowerShell@2
           displayName: 'Clone Source Control Repository To Workspace'
           inputs:
             targetType: 'inline'
             script: |
               write-host "$(Build.RequestedFor)"
               write-host "$(Build.RequestedForEmail)"
               write-host "$(Build.Repository.Uri)"